export enum UsersModuleActions {
  CREATE = 'create_user',
  READ = 'read_user',
  UPDATE = 'update_user',
  DELETE = 'delete_user',
  BLOCK = 'block_user',
  UNBLOCK = 'unblock_user',
  CREATE_OPERATOR = 'create_operator',
  READ_OPERATOR = 'read_user',
  UPDATE_OPERATOR = 'update_user',
  DELETE_OPERATOR = 'delete_user',
  CAN_ALL_OPERATOR = 'can_all_operator',
  UPDATE_PROFILE = 'update_profile',
  CAN_ALL = 'can_all_user',
}
